shell="fish"

[window]
title = "spellcaster"
padding = {x=5, y=7}
dynamic_padding=true

[font]
size = 10.3

[font.normal]
family = "Monaspace Neon"
# family = "Monaspace Neon Var"
# family = "Monaspace Argon"
# family = "Monaspace Argon Var"
# family = "Monaspace Krypton"
# family = "Monaspace Krypton Var"
# family = "Monaspace Radon"
# family = "Monaspace Radon Var"
# family = "Monaspace Xenon"
# family = "Monaspace Xenon Var"
# family = "JetBrains Mono Nerd Font"
style="Regular"

[colors.primary]
background = "#09090b"
foreground = "#F4E6D2"

[colors.normal]
black = "#221E1E"
red = "#CA3F3F"
green = "#989F56"
yellow = "#E39C45"
blue = "#517894"
magenta = "#C45497"
cyan = "#629386"
white = "#B6A8A5"

[colors.bright]
black = "#423939"
red = "#d56767"
green = "#aeb474"
yellow = "#eab471"
blue = "#6a92ae"
magenta = "#d17aae"
cyan = "#7fa99e"
white = "#F4E6D2"
